version: '2'

services:

  # piensa/deeplearning has jupyter, ros, tensorflow and keras.
  jupyter:
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - "8888:8888"
    volumes_from:
      - sdcdata

  sdcdata:
    image: piensa/sdcdata
    command: /bin/true
    volumes:
      - /data
